### ISSUE TITLE
Feature Clear Display

### ISSUE THREAD

**Issue by Kajochi** [neuefische/cgn-java-23-2-teamproject-finance#16]
# User story
As a user, I want to have clear and structured presentation of the add and update/ delete fields, so I can orientate me better on the website.

# Acceptance criteria

- [ ] The add and update/ delete fields are not visible at the same time.
- [ ] The user can navigate to the add and update/ delete fields with buttons.
 
# Tasks
- Frontend
- [ ] add routes or modal for add and update/ delete fields 

# Sprint Ready Checklist 
1. - [x] Acceptance criteria defined 
2. - [x] Team understands acceptance criteria 
3. - [x] Team has defined solution / steps to satisfy acceptance criteria 
4. - [x] Acceptance criteria is verifiable / testable
