### ISSUE TITLE
Add BigDecimal to amount and creation date

### ISSUE THREAD

**Issue by eliasYazdani** [neuefische/cgn-java-23-2-teamproject-finance#19]
# User story
As a  user, I want to have creation date and able to give decimal amount.

# Acceptance criteria
- [ ] Able to input date in transaction update/add
- [ ] Able to input amount in decimal format

# Tasks
- Frontend
- [ ] Use step width for amount field to change it to decimal 
- [ ] Add payment date variable to Transaction type in model
- [ ] Add an input field to Update/Add pop up for payment date
- [ ] Add "€“ to amount field 
- [ ] Change Buchung/Ändern button to pencil icon

- Backend
- [ ] Change amount from number to big decimal
- [ ] Add new payment date variable in Transaction

# Sprint Ready Checklist 
1. - [x] Acceptance criteria defined 
2. - [x] Team understands acceptance criteria 
3. - [x] Team has defined solution / steps to satisfy acceptance criteria 
4. - [x] Acceptance criteria is verifiable / testable
