### ISSUE TITLE
Income/ expenses add

### ISSUE THREAD

**Issue by Kajochi** [neuefische/cgn-java-23-2-teamproject-finance#4]
# User story
As a user, I want to create income or expenses , so I can store them.

# Acceptance criteria
- [ ] the user has the possibility to enter an input and send it via a button

#Tasks (for Developer)

- [ ] frontend
   - [ ] Input-field for description and the amount in a  form tag
   - [ ] add-button in a  form tag
   - [ ] radio-button to define if it is income or expenses in a  form tag
   -  [ ] implement the frontend for the interface
   -  [ ] create a export type model
   - [ ] implement the interface in App.tsx component
- [ ] backend 
   - [ ] create rest-controller-class, 
   - [ ] service-class
   - [ ] repo-class
   - [ ] model-class
   - [ ] implement tests (Unit, Integration)

# Sprint Ready Checklist 
1. - [ ] Acceptance criteria defined 
2. - [ ] Team understands acceptance criteria 
3. - [ ] Team has defined solution / steps to satisfy acceptance criteria 
4. - [ ] Acceptance criteria is verifiable / testable 
5. - [ ] External / 3rd Party dependencies identified
