### ISSUE TITLE
Implement Category RadioButton

### ISSUE THREAD

**Issue by Kajochi** [neuefische/cgn-java-23-2-teamproject-finance#6]
# User story
As a User, I want to select the category of the added posting, so I can sort the postings.

# Acceptance criteria

- [ ] The user can select the category of an added posting with a radio button

#Task for Developer
- Frontend
- [ ] add radio button on addPosting component
- [ ] create useState for value of the radio button
- [ ] add category field in addPosting method
- [ ] 
- Backend
- [ ] add category field in constructor of PostingModel
- [ ] new Unit tests
- [ ] check integration tests

# Sprint Ready Checklist 
1. - [x] Acceptance criteria defined 
2. - [x] Team understands acceptance criteria 
3. - [x] Team has defined solution / steps to satisfy acceptance criteria 
4. - [ ] Acceptance criteria is verifiable / testable
