### ISSUE TITLE
Feature read

### ISSUE THREAD

**Issue by Ben-21** [neuefische/cgn-java-23-2-teamproject-finance#7]
# Feature read
As a user, I want to see all the postings as a list, so I can check them.

# Acceptance criteria
- [ ] User can see a list of all the postings. 

# Tasks
- Frontend
- [ ] Make a component for presenting a posting
- [ ] Make a component for presenting a list of postings
- [ ] add id to type Posting
- [ ] create axios.get in useEffect
- [ ] create useState for Postings (list)
- Backend
- [ ] add GetMapping to postingController
- [ ] create getPostings in PostingRepo, PostingService
- [ ] write unit- and integration-tests

# Sprint Ready Checklist 
1. - [x] Acceptance criteria defined 
2. - [x] Team understands acceptance criteria 
3. - [x] Team has defined solution / steps to satisfy acceptance criteria 
4. - [x] Acceptance criteria is verifiable / testable
