### ISSUE TITLE
Feature update

### ISSUE THREAD

**Issue by Ben-21** [neuefische/cgn-java-23-2-teamproject-finance#8]
# Feature update
As a user, I want to update one posting by clicking an edit button, so I can change description, amount and category.

# Acceptance criteria
- [ ] There is an edit button which opens a detailed view of one posting
- [ ] User can change all values of a posting, except of id
- [ ] There is a save button
- [ ] There is a close or cancel button, which gives the opportunity to leave the update process without saving

# Tasks
- Frontend
- [ ] Make a component for updating a posting - including save- and cancel-buttons
- [ ] create axios.put in useEffect

- Backend
- [ ] add PutMapping to postingController
- [ ] create updatePostings() in PostingRepo, PostingService
- [ ] write unit- and integration-tests

# Sprint Ready Checklist 
1. - [x] Acceptance criteria defined 
2. - [x] Team understands acceptance criteria 
3. - [x] Team has defined solution / steps to satisfy acceptance criteria 
4. - [x] Acceptance criteria is verifiable / testable
