### ISSUE TITLE
Feature delete

### ISSUE THREAD

**Issue by Ben-21** [neuefische/cgn-java-23-2-teamproject-finance#9]
# Feature update
As a user, I want to delete a posting by clicking a delete button.

# Acceptance criteria
- [ ] There is a delete button which deletes a posting
- [ ] The list of existing postings shall be updated after deleting 

# Tasks
- Frontend
- [ ] Make a delete button next to the edit button in Posting.tsx
- [ ] create axios.delete in useEffect

- Backend
- [ ] add DeleteMapping to postingController
- [ ] create deletePosting() in PostingRepo, PostingService
- [ ] write unit- and integration-tests

# Sprint Ready Checklist 
1. - [x] Acceptance criteria defined 
2. - [x] Team understands acceptance criteria 
3. - [x] Team has defined solution / steps to satisfy acceptance criteria 
4. - [x] Acceptance criteria is verifiable / testable
